#!/usr/bin/env python3
"""Emit research/corpus/sources/g2-generated.json (F04 many-small-file trees, F15 sparse files,
F17 duplicate trees, F19 metadata-heavy filesystem trees, F20 adversarial/high-entropy inputs)
from the declarative table below.

    python make_sources.py [--check-only]

--check-only  print the JSON to stdout instead of writing the file.

Output is deterministic (stable key order, indent=2, trailing newline).  Stdlib only; runs
under Windows or WSL Python.

Docker was unavailable in this session (com.docker.service requires admin to start in a
non-admin Windows session, so the docker-desktop WSL VM never came up) so F04 and F19 use
already-provisioned real trees (via kind=derive + copy-item) instead of fresh docker-export
items; see PROGRESS.md for the record. All five families' generated items use the scripts in
this directory (see each script's own docstring for its construction and which splits it is
meant for); metadata_tree.py's "matrix" profile and hardlink_farm.py's "linkstore" model are
each generator's own held-out construction, not reused in tuning/validation.
"""

import argparse
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
SOURCES = REPO / "research" / "corpus" / "sources" / "g2-generated.json"
GEN = "research/corpus/generators/g2-generated"

# ---------------------------------------------------------------------------------------
# licenses


def lic(name, redistributable, attribution, notes=""):
    return {"spdx_or_name": name, "redistributable": redistributable, "attribution": attribution, "notes": notes}


GENERATED_LIC = lic("CC0-1.0 (generated by Entrybound research scripts)", True, "Entrybound research corpus generators",
                    "Synthetic data; statistics reflect the generator's model, not any real system. "
                    "All names/addresses/keys are invented or seeded pseudorandom; no real personal data or secrets.")
MIXED_PACKAGE_LIC = lic("LicenseRef-mixed-per-package", False, "authors of each vendored/installed package",
                        "aggregate of third-party packages under their own licenses (overwhelmingly permissive OSS, "
                        "some copyleft possible); not audited package by package, so treated as non-redistributable: "
                        "only hashes are committed. Reused here (via kind=derive from an already-provisioned F03 item) "
                        "as real many-small-files / real duplicate-tree content; carries the same license disposition "
                        "as the source item.")
LINUX_LIC = lic("GPL-2.0-only WITH Linux-syscall-note", True, "Linus Torvalds and Linux kernel contributors",
                "individual files carry SPDX identifiers (some dual-licensed); see COPYING and LICENSES/. "
                "Reused here (via kind=derive from f01-heldout-linux-6-6-src) as a real many-small-files tree "
                "(Documentation/ subtree only).")

# ---------------------------------------------------------------------------------------
# helpers


def item(item_id, family, split, scale, kind, rog, recipe, license_, group, description, notes=None, tags=None):
    d = {"item_id": item_id, "family": family, "split": split, "scale": scale, "kind": kind,
         "real_or_generated": rog, "recipe": recipe, "license": license_, "independence_group": group,
         "description": description}
    if notes:
        d["notes"] = notes
    if tags:
        d["tags"] = tags
    return d


def gen(script, seed, params):
    return {"script": f"{GEN}/{script}", "seed": seed, "params": params}


def copy_whole(from_item, src=None, dest=None):
    st = {"op": "copy-item", "from_item": from_item}
    if src:
        st["src"] = src
    if dest:
        st["dest"] = dest
    return st


def derive(from_item, steps):
    return {"from_items": [from_item], "steps": steps}


ITEMS = []

# =======================================================================================
# F04 many-small-file trees
# =======================================================================================
ITEMS += [
    item("f04-tuning-sourcelike", "F04", "tuning", "small", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42001, {"model": "sourcelike", "files": 2200})},
         GENERATED_LIC, "ebrc-g2-f04-sourcelike",
         "Generated project/source-tree-like hierarchy: Zipf-weighted directory fan-out, lognormal file sizes, "
         "synthetic code/doc/config text, tiny PNG icons, ~3% empty files (__init__.py, .gitkeep).",
         tags=["generated"]),
    item("f04-tuning-maildir", "F04", "tuning", "medium", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42002, {"model": "maildir", "files": 15000, "users": 15})},
         GENERATED_LIC, "ebrc-g2-f04-maildir",
         "Generated Maildir++ mail store: per-user cur/new/tmp/IMAP-subfolders, RFC 5322 synthetic messages, "
         "occasional base64 attachments, dovecot-like index/uidlist files.",
         tags=["generated"]),
    item("f04-validation-objstore", "F04", "validation", "medium", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42003, {"model": "objstore", "files": 25000, "ccache_fraction": 0.35})},
         GENERATED_LIC, "ebrc-g2-f04-objstore",
         "Generated content-addressed stores: real-format git loose objects (zlib-deflated, SHA-1 fan-out) plus a "
         "ccache-like two-level hashed cache of small binary result files.",
         tags=["generated"]),
    item("f04-validation-bootstrap-npm-modules", "F04", "validation", "medium", "derive", "derived-from-real",
         derive("f03-validation-bootstrap-npm-node-modules", [copy_whole("f03-validation-bootstrap-npm-node-modules")]),
         MIXED_PACKAGE_LIC, "twbs-bootstrap-node-modules",
         "Real many-small-files tree: `npm install` node_modules of twbs/bootstrap's package.json/package-lock.json "
         "(34.7k files), reused whole from the already-provisioned F03 vendor-tree item.",
         notes="Same underlying bytes as f03-validation-bootstrap-npm-node-modules (F03: dependency/vendor trees); "
               "here it is the many-small-files object of study rather than the vendoring/dedup one."),
    item("f04-heldout-linux-docs", "F04", "heldout", "medium", "derive", "derived-from-real",
         derive("f01-heldout-linux-6-6-src", [copy_whole("f01-heldout-linux-6-6-src", src="Documentation")]),
         LINUX_LIC, "linux-kernel-documentation",
         "Real many-small-files tree: the Documentation/ subtree of the Linux 6.6 release (thousands of .rst/.txt "
         "files, deep nesting), reused from the already-provisioned F01 heldout source-tree item.",
         notes="Held-out: distinct independence group from every tuning/validation F04 item. Derives from a "
               "heldout-split source (f01-heldout-linux-6-6-src), so no tuning/validation split is exposed."),
    item("f04-heldout-pypi-site-packages", "F04", "heldout", "medium", "derive", "derived-from-real",
         derive("f03-heldout-pypi-web-site-packages", [copy_whole("f03-heldout-pypi-web-site-packages")]),
         MIXED_PACKAGE_LIC, "pypi-web-service-stack-sitepkgs",
         "Real many-small-files tree: pip-installed site-packages of a small web-service dependency stack (12.5k "
         "files), reused whole from the already-provisioned F03 heldout vendor-tree item.",
         notes="Held-out: distinct independence group from every tuning/validation F04 item; derives from a "
               "heldout-split source (f03-heldout-pypi-web-site-packages)."),
]

# =======================================================================================
# F15 sparse files
# =======================================================================================
ITEMS += [
    item("f15-tuning-vmraw", "F15", "tuning", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51001,
                           {"model": "vm-raw", "disk_bytes": 268435456, "fill_fraction": 0.1})},
         GENERATED_LIC, "ebrc-g2-f15-vmraw",
         "Generated raw VM disk image: protective MBR + GPT (valid CRCs, backup GPT), BIOS-boot partition, "
         "FAT32-like ESP, ext4-like root partition (superblock backups, flex_bg bitmaps, partial inode tables, "
         "zero-filled journal, mixed file-data extents). Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-tuning-dbprealloc", "F15", "tuning", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51002, {"model": "db-prealloc", "scale": 0.5})},
         GENERATED_LIC, "ebrc-g2-f15-dbprealloc",
         "Generated database/queue preallocation sparse files: Kafka-like log segments with sparse index files, "
         "bbolt-like scattered page file, InnoDB-like page-compressed tablespace (punch-hole per page), LMDB-like "
         "MDB_WRITEMAP data file. Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-validation-edgecases", "F15", "validation", "small", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51003, {"model": "edge-cases"})},
         GENERATED_LIC, "ebrc-g2-f15-edgecases",
         "Generated small sparse boundary cases: all-hole, first/last-byte-only, alternating 4 KiB data/hole, "
         "1-byte islands at block edges, written (unallocated-looking) zeros, odd sizes. <=16 MiB total. "
         "Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-validation-fragmented", "F15", "validation", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51004, {"model": "fragmented", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f15-fragmented",
         "Generated many-small-extents sparse files: BitTorrent-like partially downloaded files at several piece "
         "sizes, a regular 4 KiB-every-64 KiB lattice, a Bernoulli block pattern, a log with random hole runs. "
         "Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-heldout-hugehole", "F15", "heldout", "large", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51005, {"model": "huge-hole", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f15-hugehole",
         "Generated huge-hole/single-extent sparse files: multi-GiB images with one data extent at the end, start "
         "or middle, an all-hole file, and 8 MiB fixed-size journal-like files. Verified with SEEK_DATA/SEEK_HOLE.",
         notes="Held-out generated item: apparent size is multi-GiB (large scale) but actual written bytes are "
               "small (sparse), so materialized cost stays modest.",
         tags=["generated"]),
    item("f15-heldout-coredump", "F15", "heldout", "medium", "generate", "generated",
         {"generator": gen("sparse_coredump.py", 51006,
                           {"cores": 2, "heap_mib": 24, "arenas": 2, "arena_mib": 24, "threads": 3, "stack_mib": 6,
                            "wal_segments": 2, "wal_segment_mib": 32})},
         GENERATED_LIC, "ebrc-g2-f15-coredump",
         "Generated sparse ELF64 core dumps (dump_skip semantics: whole-zero pages become holes) and fixed-size "
         "write-ahead-log segments. A separate generator from sparse_layouts.py so the heldout layout model differs "
         "from every tuning/validation F15 item. Verified with SEEK_DATA/SEEK_HOLE.",
         notes="Held-out generator (distinct script from sparse_layouts.py, per its own docstring).",
         tags=["generated"]),
]

# =======================================================================================
# F17 duplicate trees
# =======================================================================================
ITEMS += [
    item("f17-tuning-duptree-mixed", "F17", "tuning", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61001,
                           {"base_files": 1200, "exact_copies": ["copy-a", "copy-b"],
                            "vendored_subtree": {"count": 4, "min_files": 15}, "renamed_files": 40})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-mixed",
         "Generated base project tree with 2 exact (cp -a) copies, a subtree vendored into 4 third_party/"
         "node_modules-style paths, and 40 file-level renamed duplicates.",
         tags=["generated"]),
    item("f17-tuning-duptree-nested", "F17", "tuning", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61002,
                           {"base_files": 1000, "renamed_copies": ["renamed-a", "renamed-b", "renamed-c"],
                            "nested_copy": True})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-nested",
         "Generated base project tree with 3 renamed copies (same bytes, new mtimes/normalised modes as `cp -r` "
         "without -p) and a full backup-inside-project nested copy.",
         tags=["generated"]),
    item("f17-validation-real-yq-vendor-8x", "F17", "validation", "medium", "derive", "derived-from-real",
         derive("f03-validation-yq-go-mod-vendor",
               [copy_whole("f03-validation-yq-go-mod-vendor", dest=f"copy-{i:02d}") for i in range(1, 9)]),
         MIXED_PACKAGE_LIC, "real-yq-vendor-8x",
         "Real duplicate-tree: 8 independent `cp -a` copies of mikefarah/yq's `go mod vendor` tree (766 files each), "
         "reused from the already-provisioned F03 vendor-tree item.",
         notes="Same underlying bytes as f03-validation-yq-go-mod-vendor; here the object of study is the 8x exact "
               "duplication, not the vendoring itself."),
    item("f17-validation-duptree-vendor", "F17", "validation", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61003,
                           {"base_files": 1500, "vendored_subtree": {"count": 6, "min_files": 10},
                            "exact_copies": ["mirror"]})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-vendor",
         "Generated base project tree with a subtree vendored into 6 third_party/node_modules-style paths (deeper "
         "nested vendoring, e.g. node_modules/x/node_modules/y) plus one full exact mirror copy.",
         tags=["generated"]),
    item("f17-heldout-duptree-mono", "F17", "heldout", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61004,
                           {"base_files": 1400, "exact_copies": ["copy-1"],
                            "vendored_subtree": {"count": 8, "min_files": 20}})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-mono",
         "Generated base project tree with one exact copy and a subtree vendored into 8 separate paths (heavier "
         "vendoring fan-out than any tuning/validation F17 item).",
         notes="Held-out: distinct independence group and distinct topology (heavier vendoring fan-out) from every "
               "tuning/validation F17 item; fresh seed, no shared bytes.",
         tags=["generated"]),
    item("f17-heldout-duptree-renamed", "F17", "heldout", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61005,
                           {"base_files": 900, "renamed_files": 150, "nested_copy": True,
                            "renamed_copies": ["r1", "r2"]})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-renamed",
         "Generated base project tree with 150 file-level renamed duplicates, a nested backup-inside-project copy, "
         "and 2 renamed full-tree copies.",
         notes="Held-out: distinct independence group from every tuning/validation F17 item; fresh seed, no shared "
               "bytes.",
         tags=["generated"]),
]

# =======================================================================================
# F19 metadata-heavy filesystem trees
# =======================================================================================
ITEMS += [
    item("f19-tuning-zoo", "F19", "tuning", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71001, {"profile": "zoo", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-zoo",
         "Generated broad-coverage metadata tree: exhaustive permission matrix (all 4096 modes), varied uids/gids, "
         "user.*/trusted.*/security.* xattrs, access+default POSIX ACLs, hardlink groups (incl. 1000-link group), "
         "symlinks (relative/absolute/dangling/loop/chain), FIFOs, device nodes, a unix socket, Unicode/hostile/"
         "non-UTF-8 names, extreme mtimes (1901..2446).",
         tags=["generated"]),
    item("f19-tuning-rsnapshot-a", "F19", "tuning", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71002,
                           {"model": "rsnapshot", "base_files": 1500, "snapshots": 8, "change_fraction": 0.04})},
         GENERATED_LIC, "ebrc-g2-f19-rsnapshot-a",
         "Generated rsync --link-dest/rsnapshot-style rotating backup snapshots: oldest snapshot a full copy, each "
         "newer snapshot hardlinking unchanged files, writing changed files as new inodes, renaming directories "
         "(files stay hardlinked) and breaking links on metadata-only changes.",
         tags=["generated"]),
    item("f19-validation-deep", "F19", "validation", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71003, {"profile": "deep", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-deep",
         "Generated depth/width metadata tree: 1000-level one-character directory chain, near-PATH_MAX name chain, "
         "20000-entry directory, default-ACL inheritance through a subtree, symlinks climbing hundreds of levels, "
         "hardlinks between deepest and shallowest directories, xattrs on directories, non-Latin scripts.",
         tags=["generated"]),
    item("f19-validation-rsnapshot-b", "F19", "validation", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71004,
                           {"model": "rsnapshot", "base_files": 2000, "snapshots": 6, "change_fraction": 0.08})},
         GENERATED_LIC, "ebrc-g2-f19-rsnapshot-b",
         "Generated rsync --link-dest/rsnapshot-style rotating backup snapshots (independent seed/topology from "
         "f19-tuning-rsnapshot-a: more base files, fewer/higher-churn snapshots).",
         tags=["generated"]),
    item("f19-heldout-matrix", "F19", "heldout", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71005, {"profile": "matrix", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-matrix",
         "Generated owner x group x mode x ACL-variant cross-product metadata tree: xattr value-size ladder to the "
         "ext4 single-block limit, 255-byte xattr names, random Unicode/invalid-byte names, an alternatives-style "
         "symlink farm, a bin/sbin/usr-bin hardlink farm, uniformly random ext4-range timestamps, device nodes with "
         "random major/minor numbers.",
         notes="Held-out construction (metadata_tree.py's own docstring): a different profile from zoo/deep, never "
               "used in tuning/validation.",
         tags=["generated"]),
    item("f19-heldout-linkstore", "F19", "heldout", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71006, {"model": "linkstore", "packages": 40, "versions_max": 4})},
         GENERATED_LIC, "ebrc-g2-f19-linkstore",
         "Generated Nix-store-like tree after `nix-store --optimise`: read-only versioned package directories, "
         "identical files replaced by hardlinks into a content-addressed .links/ directory, .drv text files, and "
         "profile/gcroot symlink chains.",
         notes="Held-out construction (hardlink_farm.py's own docstring): a different model from rsnapshot, never "
               "used in tuning/validation.",
         tags=["generated"]),
]

# =======================================================================================
# F20 adversarial/high-entropy inputs
# =======================================================================================
ITEMS += [
    item("f20-tuning-csprng", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("csprng_files.py", 81001, {"mode": "files", "count": 60, "max_mib": 4})},
         GENERATED_LIC, "ebrc-g2-f20-csprng",
         "Generated maximal-entropy files from a seeded CSPRNG (SHAKE-256 counter mode): a fixed list of boundary "
         "sizes (powers of two +-1, 4 KiB edges, every gear-norm-v1 v2 policy's min/target/max +-1) plus "
         "log-uniform-sized files.",
         tags=["generated"]),
    item("f20-tuning-gear-extremes", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("gear_extremes.py", 81002, {"size_mib": 16, "dedup_blob_mib": 2, "dedup_copies": 6})},
         GENERATED_LIC, "ebrc-g2-f20-gear-extremes",
         "Generated CDC-adversarial inputs for the frozen gear-norm-v1 chunker: max-forcing (every chunk exactly "
         "max, i.e. CDC degenerates to fixed-size), min-forcing (every chunk exactly min), dedup-evading exact "
         "copies of a max-forcing blob at distinct residues, and boundary-length files. Verified against a "
         "vectorised reference chunker (cross-checked byte-for-byte against entrybound::chunker; see cdc_verify.sh).",
         tags=["generated"]),
    item("f20-tuning-bombs-dense", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("compressible_bombs.py", 81003, {"mode": "dense", "scale": 0.3})},
         GENERATED_LIC, "ebrc-g2-f20-bombs-dense",
         "Generated highly compressible / codec-window-defeating files: dense zeros, single-byte and ASCII runs, "
         "a counter-incrementing log, random periods just beyond common match windows (deflate/zstd/brotli/xz), "
         "near-zero files with sparse random bytes, a repeated random block.",
         tags=["generated"]),
    item("f20-validation-aesctr", "F20", "validation", "medium", "generate", "generated",
         {"generator": gen("aes_ctr_ciphertext.py", 81004, {"plaintext_mib": 16, "keystream_mib": 32, "containers": 150})},
         GENERATED_LIC, "ebrc-g2-f20-aesctr",
         "Generated AES-256-CTR ciphertext (openssl enc, KAT-verified against NIST SP 800-38A F.5.5): near-duplicate "
         "plaintext versions under fresh IVs (no shared ciphertext) and under a reused IV (nonce-reuse misuse: "
         "ciphertext bytes shared wherever plaintext matches), pure keystream, and generic encrypted containers.",
         tags=["generated"]),
    item("f20-validation-bombs-compressed", "F20", "validation", "large", "generate", "generated",
         {"generator": gen("compressible_bombs.py", 81005,
                           {"mode": "compressed", "gz_gib": 1, "xz_gib": 1, "bz2_gib": 1, "zst_gib": 2,
                            "nested_gib": 1, "zip_entries": 8, "zip_entry_mib": 64, "tar_members": 4})},
         GENERATED_LIC, "ebrc-g2-f20-bombs-compressed",
         "Generated small compressed containers with huge expansion ratios: gzip/xz/bzip2/zstd of all-zero streams, "
         "triple-nested gzip, a flat zip of zero entries, a nested zip-of-zips, a tar.zst of zero members, and a "
         "POSIX tar with a 1 TiB sparse member (GNU tar --sparse).",
         notes="Materialized bytes are tiny (containers only) even though expanded/apparent content reaches "
               "multiple GiB and one 1 TiB sparse tar member; scale label reflects the adversarial expansion ratio, "
               "not on-disk cost.",
         tags=["generated"]),
    item("f20-validation-sparsedup", "F20", "validation", "medium", "generate", "generated",
         {"generator": gen("entropy_sparse_dup.py", 81006,
                           {"files": 16, "file_mib": 8, "blobs": 10, "blob_kib": [64, 256, 1024, 4096], "max_copies": 6})},
         GENERATED_LIC, "ebrc-g2-f20-sparsedup",
         "Generated maximal-entropy files with sparse exact duplication: a cdc-friendly variant (random blob copies "
         "at random offsets; CDC re-synchronises and finds duplicate chunks) and a cdc-hostile variant (gear-norm-v1 "
         "max-forcing everywhere outside the protected blob copies; offsets chosen so no chunk is ever duplicated "
         "although the blobs are). Verified with the reference chunker (0 duplicate chunks hostile, >0 friendly).",
         tags=["generated"]),
    item("f20-heldout-chacha-files", "F20", "heldout", "small", "generate", "generated",
         {"generator": gen("chacha20_containers.py", 81007, {"mode": "files", "count": 150, "xm": 16384, "cap_mib": 8, "sealed": 60})},
         GENERATED_LIC, "ebrc-g2-f20-chacha",
         "Generated ChaCha20 keystream and encrypted-container-like inputs (openssl enc -chacha20, cross-checked "
         "against an independent pure-Python RFC 8439 block function): Pareto-sized files fanned out by key byte, "
         "and generic sealed containers.",
         notes="Held-out: a different CSPRNG/cipher, size distribution and container layout from the "
               "tuning/validation F20 items (csprng_files.py, aes_ctr_ciphertext.py); per chacha20_containers.py's "
               "own docstring.",
         tags=["generated"]),
    item("f20-heldout-chacha-volume", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("chacha20_containers.py", 81008, {"mode": "volume", "volume_mib": 256, "backup_mib": 128})},
         GENERATED_LIC, "ebrc-g2-f20-chacha",
         "Generated encrypted-volume-like image: a 2 MiB header area (text metadata, random key slots) followed by "
         "ChaCha20 keystream, plus a sealed backup container. Same independence group and construction family as "
         "f20-heldout-chacha-files, at volume scale.",
         tags=["generated"]),
    item("f20-heldout-bombvariants", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("bomb_variants.py", 81009, {"scale": 0.15})},
         GENERATED_LIC, "ebrc-g2-f20-bombvariants",
         "Generated bomb-like and near-bomb inputs: brotli/lz4/lzip/multiblock-xz/multimember-gzip of all-zero "
         "streams, a 70000-empty-entry zip, a 200000-empty-member tar.gz, near-zero dense files.",
         notes="Held-out: a different generator from compressible_bombs.py (other codecs and container shapes, "
               "entry-count rather than byte-count blow-ups); per bomb_variants.py's own docstring.",
         tags=["generated"]),
    item("f20-heldout-gearstraddle", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("gear_straddle.py", 81010, {"size_mib": 16})},
         GENERATED_LIC, "ebrc-g2-f20-gearstraddle",
         "Generated CDC-adversarial inputs targeting gear-norm-v1 mask transitions and near-misses: late-flood "
         "(matches every late mask but one early mask), near-miss (a bit set one above every policy's mask so "
         "nothing ever cuts), target-minus-one, alternating-min-max, trigger-bursts, and shifted-duplicate "
         "max-forcing blobs. Verified with the reference chunker.",
         notes="Held-out: a different generator from gear_extremes.py (targets mask transitions/near-misses "
               "instead of pure min/max forcing); per gear_straddle.py's own docstring.",
         tags=["generated"]),
]

DOC_NOTES = (
    "g2-generated corpus group: F04 many-small-file trees, F15 sparse files, F17 duplicate trees, F19 "
    "metadata-heavy filesystem trees, F20 adversarial/high-entropy inputs. Generated by "
    "research/corpus/generators/g2-generated/make_sources.py; edit the script, not this file. All items are "
    "materialized by the generator scripts in research/corpus/generators/g2-generated/ (each script's docstring "
    "documents its constructions, parameters and which split(s) it targets) except the F04 items reusing an "
    "already-provisioned F01/F03 item (kind=derive + copy-item): those carry real license terms from the source "
    "item. Docker was unavailable in this session (com.docker.service requires admin to start; the docker-desktop "
    "WSL VM never came up), so no docker-export items were added to this group; F04/F19 rely on generated content "
    "plus (F04 only) already-provisioned real trees instead of fresh docker exports of /usr/include, /usr/share/doc "
    "or /etc. F20's gear-norm-v1 adversarial generators (gear_extremes.py, gear_straddle.py, entropy_sparse_dup.py) "
    "embed a byte-identical vectorised reference chunker cross-checked against the real entrybound::chunker via "
    "cdc_verify.sh/cdc_verify.py (0 mismatches across all four v2 policies on every generated file, checked during "
    "authoring). Two stray probe scripts (.g2probe.py depth-walk smoke test, .g2probe.sh compressible_bombs "
    "determinism smoke test) and an unrelated leftover /root/eb-research/generated/EXP-SMOKE-000 directory (an "
    "ebr runner smoke-test artifact, not part of this corpus group) were found during resume; see PROGRESS.md for "
    "disposition. research/corpus/generators/g2-generated/ext4_image.py (a kind=derive generator that packs an "
    "existing item into a sparse ext4 image with mke2fs/debugfs/e2fsck) was reviewed and works (verified against "
    "e2fsprogs 1.47.0) but is not used by any item in this file; it remains available for future F15/F16 expansion."
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()
    items = json.loads(json.dumps(ITEMS))
    doc = {"schema": "ebrc-sources-v1", "notes": DOC_NOTES, "items": items}
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    if args.check_only:
        print(text)
        return
    SOURCES.parent.mkdir(parents=True, exist_ok=True)
    tmp = SOURCES.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, SOURCES)
    print(f"wrote {SOURCES} ({len(items)} items)")


if __name__ == "__main__":
    main()
