#!/usr/bin/env python3
"""Emit research/corpus/sources/g2-generated.json (F04 many-small-file trees, F15 sparse files,
F17 duplicate trees, F19 metadata-heavy filesystem trees, F20 adversarial/high-entropy inputs)
from the declarative table below.

    python make_sources.py [--check-only]

--check-only  print the JSON to stdout instead of writing the file.

Output is deterministic (stable key order, indent=2, trailing newline).  Stdlib only; runs
under Windows or WSL Python.

Docker was unavailable in this session (com.docker.service requires admin to start in a
non-admin Windows session, so the docker-desktop WSL VM never came up) so F04 and F19 use
already-provisioned real trees (via kind=derive + copy-item) instead of fresh docker-export
items; see PROGRESS.md for the record. All five families' generated items use the scripts in
this directory (see each script's own docstring for its construction and which splits it is
meant for); metadata_tree.py's "matrix" profile and hardlink_farm.py's "linkstore" model are
each generator's own held-out construction, not reused in tuning/validation.
"""

import argparse
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
SOURCES = REPO / "research" / "corpus" / "sources" / "g2-generated.json"
GEN = "research/corpus/generators/g2-generated"

# ---------------------------------------------------------------------------------------
# licenses


def lic(name, redistributable, attribution, notes=""):
    return {"spdx_or_name": name, "redistributable": redistributable, "attribution": attribution, "notes": notes}


GENERATED_LIC = lic("CC0-1.0 (generated by Entrybound research scripts)", True, "Entrybound research corpus generators",
                    "Synthetic data; statistics reflect the generator's model, not any real system. "
                    "All names/addresses/keys are invented or seeded pseudorandom; no real personal data or secrets.")
MIXED_PACKAGE_LIC = lic("LicenseRef-mixed-per-package", False, "authors of each vendored/installed package",
                        "aggregate of third-party packages under their own licenses (overwhelmingly permissive OSS, "
                        "some copyleft possible); not audited package by package, so treated as non-redistributable: "
                        "only hashes are committed. Reused here (via kind=derive from an already-provisioned F03 item) "
                        "as real many-small-files / real duplicate-tree content; carries the same license disposition "
                        "as the source item.")
LINUX_LIC = lic("GPL-2.0-only WITH Linux-syscall-note", True, "Linus Torvalds and Linux kernel contributors",
                "individual files carry SPDX identifiers (some dual-licensed); see COPYING and LICENSES/. "
                "Reused here (via kind=derive from f01-heldout-linux-6-6-src) as a real many-small-files tree "
                "(Documentation/ subtree only).")

# ---------------------------------------------------------------------------------------
# helpers


def item(item_id, family, split, scale, kind, rog, recipe, license_, group, description, notes=None, tags=None):
    d = {"item_id": item_id, "family": family, "split": split, "scale": scale, "kind": kind,
         "real_or_generated": rog, "recipe": recipe, "license": license_, "independence_group": group,
         "description": description}
    if notes:
        d["notes"] = notes
    if tags:
        d["tags"] = tags
    return d


def gen(script, seed, params):
    return {"script": f"{GEN}/{script}", "seed": seed, "params": params}


def copy_whole(from_item, src=None, dest=None):
    st = {"op": "copy-item", "from_item": from_item}
    if src:
        st["src"] = src
    if dest:
        st["dest"] = dest
    return st


def derive(from_item, steps):
    return {"from_items": [from_item], "steps": steps}


ITEMS = []

# =======================================================================================
# F04 many-small-file trees
# =======================================================================================
ITEMS += [
    item("f04-tuning-sourcelike", "F04", "tuning", "small", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42001, {"model": "sourcelike", "files": 2200})},
         GENERATED_LIC, "ebrc-g2-f04-sourcelike",
         "Generated project/source-tree-like hierarchy: Zipf-weighted directory fan-out, lognormal file sizes, "
         "synthetic code/doc/config text, tiny PNG icons, ~3% empty files (__init__.py, .gitkeep).",
         tags=["generated"]),
    item("f04-tuning-maildir", "F04", "tuning", "medium", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42002, {"model": "maildir", "files": 15000, "users": 15})},
         GENERATED_LIC, "ebrc-g2-f04-maildir",
         "Generated Maildir++ mail store: per-user cur/new/tmp/IMAP-subfolders, RFC 5322 synthetic messages, "
         "occasional base64 attachments, dovecot-like index/uidlist files.",
         tags=["generated"]),
    item("f04-validation-objstore", "F04", "validation", "medium", "generate", "generated",
         {"generator": gen("small_file_tree.py", 42003, {"model": "objstore", "files": 25000, "ccache_fraction": 0.35})},
         GENERATED_LIC, "ebrc-g2-f04-objstore",
         "Generated content-addressed stores: real-format git loose objects (zlib-deflated, SHA-1 fan-out) plus a "
         "ccache-like two-level hashed cache of small binary result files.",
         tags=["generated"]),
    item("f04-validation-bootstrap-npm-modules", "F04", "validation", "medium", "derive", "derived-from-real",
         derive("f03-validation-bootstrap-npm-node-modules", [copy_whole("f03-validation-bootstrap-npm-node-modules")]),
         MIXED_PACKAGE_LIC, "twbs-bootstrap-node-modules",
         "Real many-small-files tree: `npm install` node_modules of twbs/bootstrap's package.json/package-lock.json "
         "(34.7k files), reused whole from the already-provisioned F03 vendor-tree item.",
         notes="Same underlying bytes as f03-validation-bootstrap-npm-node-modules (F03: dependency/vendor trees); "
               "here it is the many-small-files object of study rather than the vendoring/dedup one. Corpus "
               "round-1 critic (F04 MAJOR): content_tree_sha256 is byte-identical to its F03 source item; tagged "
               "duplicate-of below so analyses do not count it as an independent F04 sample.",
         tags=["duplicate-of:f03-validation-bootstrap-npm-node-modules"]),
    item("f04-heldout-linux-docs", "F04", "heldout", "medium", "derive", "derived-from-real",
         derive("f01-heldout-linux-6-6-src", [copy_whole("f01-heldout-linux-6-6-src", src="Documentation")]),
         LINUX_LIC, "linux-kernel-documentation",
         "Real many-small-files tree: the Documentation/ subtree of the Linux 6.6 release (thousands of .rst/.txt "
         "files, deep nesting), reused from the already-provisioned F01 heldout source-tree item.",
         notes="Held-out: distinct independence group from every tuning/validation F04 item. Derives from a "
               "heldout-split source (f01-heldout-linux-6-6-src), so no tuning/validation split is exposed."),
    item("f04-heldout-pypi-site-packages", "F04", "heldout", "medium", "derive", "derived-from-real",
         derive("f03-heldout-pypi-web-site-packages", [copy_whole("f03-heldout-pypi-web-site-packages")]),
         MIXED_PACKAGE_LIC, "pypi-web-service-stack-sitepkgs",
         "Real many-small-files tree: pip-installed site-packages of a small web-service dependency stack (12.5k "
         "files), reused whole from the already-provisioned F03 heldout vendor-tree item.",
         notes="Held-out: distinct independence group from every tuning/validation F04 item; derives from a "
               "heldout-split source (f03-heldout-pypi-web-site-packages). Corpus round-1 critic (F04 MAJOR): "
               "content_tree_sha256 is byte-identical to its F03 source item; tagged duplicate-of below so "
               "analyses do not count it as an independent F04 sample.",
         tags=["duplicate-of:f03-heldout-pypi-web-site-packages"]),
]

# Corpus round-1 critic gap (F04 real many-small-file trees, MAJOR): tuning was 100 percent generated;
# the two items just above are byte-identical to their F03 source items (34.7k/12.5k files -- the
# largest F04 file counts before this gap fix, still short of the family's 10^5-10^6 intent) and are
# now tagged duplicate_of so analyses do not double-count them as independent F04 samples. Three real
# package/ports trees close both gaps at once: each is 10^5+ files, in a fresh independence group not
# shared with any F01/F03 item or with each other.
ITEMS += [
    item("f04-tuning-real-netbsd-pkgsrc", "F04", "tuning", "medium", "download", "real",
         {"inputs": [{"name": "pkgsrc", "url": "https://cdn.netbsd.org/pub/pkgsrc/pkgsrc-2026Q2/pkgsrc.tar.xz",
                     "sha256": "f45ad7db5fd3d84887e01208ca24189e583b82765dbfb3354414480f3c563399", "size": 60074916,
                     "notes": "SHA-512 6516ee39...26996650 published at pkgsrc.tar.xz.SHA512 verified match; "
                              "NetBSD publishes MD5/SHA1/SHA512 for this file, not SHA-256, so the SHA-256 above "
                              "was computed locally from the SHA-512-verified download."}],
          "steps": [{"op": "extract", "input": "pkgsrc"}]},
         lic("BSD-2-Clause (pkgsrc infrastructure; individual packages' Makefiles/patches under their own terms)",
             True, "The NetBSD Foundation and pkgsrc contributors",
             "pkgsrc source tree (Makefiles, package descriptions, patches, PLISTs) only; no distfiles fetched."),
         "netbsd-pkgsrc",
         "Real many-small-files tree: the NetBSD pkgsrc-2026Q2 quarterly source tree snapshot, tens of thousands "
         "of per-package directories (Makefile, DESCR, PLIST, distinfo, patches/) across every pkgsrc category. "
         "Fills F04's missing 10^5-10^6 file-count tier in tuning (previously 100% generated).",
         tags=["real"]),
    item("f04-validation-real-gentoo-repo-20260915", "F04", "validation", "medium", "download", "real",
         {"inputs": [{"name": "gentoo", "url": "https://distfiles.gentoo.org/snapshots/gentoo-20260915.tar.xz",
                     "sha256": "d96560a0e30c34d6d3701295c0071b56f87a0a55a0d77645a6eef5fde853ab7e", "size": 49333192,
                     "notes": "MD5 bbcc9b5c76fb2a6b9801fae72e141585 published at gentoo-20260915.tar.xz.md5sum "
                              "verified match; SHA-256 above computed locally (Gentoo publishes MD5 + a detached "
                              "gpg signature for snapshots, not SHA-256). A dated snapshot filename is pinned "
                              "rather than the rolling 'latest' symlink, so the source stays reproducible."}],
          "steps": [{"op": "extract", "input": "gentoo"}]},
         lic("GPL-2.0 (ebuilds/eclasses; Gentoo repository content is GPL-2.0 unless a package's own metadata "
             "says otherwise)", True, "Gentoo Foundation and Gentoo contributors",
             "Portage tree (ebuilds, eclasses, Manifest/metadata.xml) only; no source distfiles fetched."),
         "gentoo-repo",
         "Real many-small-files tree: a dated Gentoo ::gentoo repository snapshot (2026-09-15), tens of thousands "
         "of per-package ebuild directories across every category. Fills F04's missing real many-small-files "
         "item in validation (medium tier, 231 MiB materialized; the held-out freebsd-ports item below is F04's "
         "large-tier real item).",
         tags=["real"]),
    item("f04-heldout-real-freebsd-ports", "F04", "heldout", "large", "git-archive", "real",
         {"git": {"repo": "https://github.com/freebsd/freebsd-ports.git",
                 "commit": "18858862d8ed65ad79acdbe3159a6760fdce0b18", "ref": "main"}},
         lic("BSD-2-Clause (Ports Collection infrastructure; individual ports' Makefiles/patches under their own "
             "terms)", True, "The FreeBSD Project",
             "Ports tree (Makefiles, pkg-descr, pkg-plist, patches) only; no distfiles fetched."),
         "freebsd-ports",
         "Held-out: real many-small-files tree, a pinned-commit git archive of the FreeBSD Ports Collection "
         "(freebsd/freebsd-ports @ 1885886, 2026-09-16) -- roughly 225k files across some 30k port directories.",
         notes="Held-out: distinct independence group (freebsd-ports) from every tuning/validation F04 item and "
               "from every other family's item.",
         tags=["real"]),
]

# =======================================================================================
# F15 sparse files
# =======================================================================================
ITEMS += [
    item("f15-tuning-vmraw", "F15", "tuning", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51001,
                           {"model": "vm-raw", "disk_bytes": 268435456, "fill_fraction": 0.1})},
         GENERATED_LIC, "ebrc-g2-f15-vmraw",
         "Generated raw VM disk image: protective MBR + GPT (valid CRCs, backup GPT), BIOS-boot partition, "
         "FAT32-like ESP, ext4-like root partition (superblock backups, flex_bg bitmaps, partial inode tables, "
         "zero-filled journal, mixed file-data extents). Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-tuning-dbprealloc", "F15", "tuning", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51002, {"model": "db-prealloc", "scale": 0.5})},
         GENERATED_LIC, "ebrc-g2-f15-dbprealloc",
         "Generated database/queue preallocation sparse files: Kafka-like log segments with sparse index files, "
         "bbolt-like scattered page file, InnoDB-like page-compressed tablespace (punch-hole per page), LMDB-like "
         "MDB_WRITEMAP data file. Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-validation-edgecases", "F15", "validation", "small", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51003, {"model": "edge-cases"})},
         GENERATED_LIC, "ebrc-g2-f15-edgecases",
         "Generated small sparse boundary cases: all-hole, first/last-byte-only, alternating 4 KiB data/hole, "
         "1-byte islands at block edges, written (unallocated-looking) zeros, odd sizes. <=16 MiB total. "
         "Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-validation-fragmented", "F15", "validation", "medium", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51004, {"model": "fragmented", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f15-fragmented",
         "Generated many-small-extents sparse files: BitTorrent-like partially downloaded files at several piece "
         "sizes, a regular 4 KiB-every-64 KiB lattice, a Bernoulli block pattern, a log with random hole runs. "
         "Verified with SEEK_DATA/SEEK_HOLE.",
         tags=["generated"]),
    item("f15-heldout-hugehole", "F15", "heldout", "large", "generate", "generated",
         {"generator": gen("sparse_layouts.py", 51005, {"model": "huge-hole", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f15-hugehole",
         "Generated huge-hole/single-extent sparse files: multi-GiB images with one data extent at the end, start "
         "or middle, an all-hole file, and 8 MiB fixed-size journal-like files. Verified with SEEK_DATA/SEEK_HOLE.",
         notes="Held-out generated item: apparent size is multi-GiB (large scale) but actual written bytes are "
               "small (sparse), so materialized cost stays modest.",
         tags=["generated"]),
    item("f15-heldout-coredump", "F15", "heldout", "medium", "generate", "generated",
         {"generator": gen("sparse_coredump.py", 51006,
                           {"cores": 2, "heap_mib": 24, "arenas": 2, "arena_mib": 24, "threads": 3, "stack_mib": 6,
                            "wal_segments": 2, "wal_segment_mib": 32})},
         GENERATED_LIC, "ebrc-g2-f15-coredump",
         "Generated sparse ELF64 core dumps (dump_skip semantics: whole-zero pages become holes) and fixed-size "
         "write-ahead-log segments. A separate generator from sparse_layouts.py so the heldout layout model differs "
         "from every tuning/validation F15 item. Verified with SEEK_DATA/SEEK_HOLE.",
         notes="Held-out generator (distinct script from sparse_layouts.py, per its own docstring).",
         tags=["generated"]),
]

# Corpus round-1 critic gap (F15 real layouts, MAJOR): all 6 F15 items were generated and validation
# had no large item. Real VM/cloud disk images are converted to sparse raw with qemu-img convert and
# hole-punched (fallocate --dig-holes) so the on-disk extent map is a deterministic function of guest
# content (research/corpus/generators/g4-binary/convert_image.sh's own documented rationale);
# fingerprint.py records every regular file's SEEK_DATA/SEEK_HOLE extent map as part of the item's
# logical_tree_sha256, so the sparse layout is verified (and pinned) automatically, and qemu-img
# compare runs as a semantic corruption check at conversion time.
ITEMS += [
    item("f15-tuning-real-ubuntu-noble-ova-raw", "F15", "tuning", "large", "build", "derived-from-real",
         {"inputs": [
             {"name": "ova", "url": "https://cloud-images.ubuntu.com/releases/noble/release-20260911/"
              "ubuntu-24.04-server-cloudimg-amd64.ova",
              "sha256": "ff79f630b7c845c0bb0f157db735837a9be4714be9e44ed54f11af156e4cc33a", "size": 594145280,
              "notes": "SHA-256 from the release SHA256SUMS; a plain tar of .ovf + .mf + a streamOptimized .vmdk"}],
          "generator": gen("shrink_real_disk_image.py", 51007,
                           {"mode": "ova-vmdk", "ova_input": "ova", "vmdk_member": "ubuntu-noble-24.04-cloudimg.vmdk",
                            "src_format": "vmdk", "dst": "ubuntu-noble-24.04-cloudimg.raw", "allow_shrink": True}),
          "output_pin": "TOFU"},
         lic("Ubuntu cloud image (per-package licenses; Canonical IP rights policy permits unmodified "
             "redistribution)", True, "Canonical Ltd.",
             "Converted vmdk->raw (qemu-img) without modifying guest content."),
         "ubuntu-noble",
         "Real sparse VM disk image: the official Ubuntu 24.04 server cloud image published as an OVA (release "
         "20260911); its streamOptimized VMDK is converted with qemu-img to a sparse raw disk and hole-punched. The "
         "OVA's VMDK declares a 10 GiB nominal disk but its GPT was built for a ~3.5 GiB disk (fdisk reports a "
         "PMBR size mismatch); shrink_real_disk_image.py proves everything beyond the PMBR-declared size is "
         "unwritten (SEEK_DATA) and truncates to it, so the item's logical size matches its real content "
         "(GPT + BIOS-boot/ESP/ext4-root partitions) rather than template padding.",
         notes="Same real-world source family as f16-ubuntu-noble-cloudimg-20260911-raw (independence_group "
               "ubuntu-noble) but a distinct published artifact (OVA/VMDK rather than the cloud qcow2) and a "
               "distinct purpose (F15 sparse-layout study rather than F16 disk-image-format study).",
         tags=["real", "sparse", "raw", "gpt", "ext4"]),
    item("f15-validation-real-debian-nocloud-raw", "F15", "validation", "large", "derive", "derived-from-real",
         {"from_items": ["f16-debian-13-nocloud-20260831-qcow2"],
          "generator": {"script": "research/corpus/generators/g4-binary/convert_image.sh", "interpreter": "bash",
                        "seed": 51008,
                        "params": {"from_item": "f16-debian-13-nocloud-20260831-qcow2",
                                   "src": "debian-13-nocloud-amd64-20260831-2587.qcow2", "src_format": "qcow2",
                                   "dst_format": "raw", "dst": "debian-13-nocloud-amd64-20260831-2587.raw"}}},
         lic("Debian image (DFSG-free packages, per-package copyright)", True, "Debian Cloud Team",
             "Converted qcow2->raw without modifying guest content; reused from the already-provisioned F16 item."),
         "debian-trixie",
         "Real sparse VM disk image (large tier): the already-provisioned F16 Debian 13 nocloud qcow2 image "
         "converted to sparse raw with qemu-img and hole-punched. Fills F15's missing validation large-tier item.",
         notes="Derives from f16-debian-13-nocloud-20260831-qcow2 (already downloaded/pinned); no new third-party "
               "bytes fetched. Distinct independence group (debian-trixie) from every other F15 item.",
         tags=["real", "sparse", "raw"]),
    item("f15-heldout-real-almalinux-genericcloud-raw", "F15", "heldout", "large", "derive", "derived-from-real",
         {"from_items": ["f16-heldout-almalinux-10-genericcloud-qcow2"],
          "generator": gen("shrink_real_disk_image.py", 51009,
                           {"mode": "gpt-partition", "from_item": "f16-heldout-almalinux-10-genericcloud-qcow2",
                            "src_relpath": "AlmaLinux-10-GenericCloud-10.2-20260817.0.x86_64.qcow2",
                            "src_format": "qcow2", "partition_label": "boot",
                            "dst": "almalinux-10-genericcloud-10.2-boot.raw"})},
         lic("AlmaLinux image (per-package licenses)", True, "AlmaLinux OS Foundation",
             "Converted qcow2->raw without modifying guest content; reused from the already-provisioned F16 "
             "heldout item."),
         "almalinux",
         "Held-out: real sparse filesystem image, the xfs `boot` partition of the already-provisioned F16 "
         "AlmaLinux 10 GenericCloud disk, extracted (kernel loop partition scan) and converted to sparse raw with "
         "qemu-img. Unlike the Ubuntu OVA tuning item, this disk's GPT genuinely fills its nominal 10 GiB (its xfs "
         "root filesystem's own superblock block count equals the partition size, confirmed with xfs_info: no PMBR "
         "size mismatch, so no lossless whole-disk shrink exists); one real partition is used instead so the item "
         "fits the scale tiers while still being the unmodified bytes of a real filesystem.",
         notes="Held-out: distinct independence group (almalinux) from every tuning/validation F15 item; derives "
               "from a heldout-split source (f16-heldout-almalinux-10-genericcloud-qcow2), so no tuning/validation "
               "split is exposed. Partition size is 1 GiB (still the large tier, just far below the 8.8 GiB the "
               "root partition alone would need, let alone the 10 GiB whole disk); see CONVERTINFO.txt in the item "
               "for the exact PMBR/xfs_info reasoning.",
         tags=["real", "sparse", "raw", "xfs"]),
]

# =======================================================================================
# F17 duplicate trees
# =======================================================================================
ITEMS += [
    item("f17-tuning-duptree-mixed", "F17", "tuning", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61001,
                           {"base_files": 1200, "exact_copies": ["copy-a", "copy-b"],
                            "vendored_subtree": {"count": 4, "min_files": 15}, "renamed_files": 40})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-mixed",
         "Generated base project tree with 2 exact (cp -a) copies, a subtree vendored into 4 third_party/"
         "node_modules-style paths, and 40 file-level renamed duplicates.",
         tags=["generated"]),
    item("f17-tuning-duptree-nested", "F17", "tuning", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61002,
                           {"base_files": 1000, "renamed_copies": ["renamed-a", "renamed-b", "renamed-c"],
                            "nested_copy": True})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-nested",
         "Generated base project tree with 3 renamed copies (same bytes, new mtimes/normalised modes as `cp -r` "
         "without -p) and a full backup-inside-project nested copy.",
         tags=["generated"]),
    item("f17-validation-real-yq-vendor-8x", "F17", "validation", "medium", "derive", "derived-from-real",
         derive("f03-validation-yq-go-mod-vendor",
               [copy_whole("f03-validation-yq-go-mod-vendor", dest=f"copy-{i:02d}") for i in range(1, 9)]),
         MIXED_PACKAGE_LIC, "real-yq-vendor-8x",
         "Real duplicate-tree: 8 independent `cp -a` copies of mikefarah/yq's `go mod vendor` tree (766 files each), "
         "reused from the already-provisioned F03 vendor-tree item.",
         notes="Same underlying bytes as f03-validation-yq-go-mod-vendor; here the object of study is the 8x exact "
               "duplication, not the vendoring itself."),
    item("f17-validation-duptree-vendor", "F17", "validation", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61003,
                           {"base_files": 1500, "vendored_subtree": {"count": 6, "min_files": 10},
                            "exact_copies": ["mirror"]})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-vendor",
         "Generated base project tree with a subtree vendored into 6 third_party/node_modules-style paths (deeper "
         "nested vendoring, e.g. node_modules/x/node_modules/y) plus one full exact mirror copy.",
         tags=["generated"]),
    item("f17-heldout-duptree-mono", "F17", "heldout", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61004,
                           {"base_files": 1400, "exact_copies": ["copy-1"],
                            "vendored_subtree": {"count": 8, "min_files": 20}})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-mono",
         "Generated base project tree with one exact copy and a subtree vendored into 8 separate paths (heavier "
         "vendoring fan-out than any tuning/validation F17 item).",
         notes="Held-out: distinct independence group and distinct topology (heavier vendoring fan-out) from every "
               "tuning/validation F17 item; fresh seed, no shared bytes.",
         tags=["generated"]),
    item("f17-heldout-duptree-renamed", "F17", "heldout", "medium", "generate", "generated",
         {"generator": gen("duplicate_tree.py", 61005,
                           {"base_files": 900, "renamed_files": 150, "nested_copy": True,
                            "renamed_copies": ["r1", "r2"]})},
         GENERATED_LIC, "ebrc-g2-f17-duptree-renamed",
         "Generated base project tree with 150 file-level renamed duplicates, a nested backup-inside-project copy, "
         "and 2 renamed full-tree copies.",
         notes="Held-out: distinct independence group from every tuning/validation F17 item; fresh seed, no shared "
               "bytes.",
         tags=["generated"]),
]

# Corpus round-1 critic gap (F17 real duplicate trees, MINOR): tuning and held-out were 100% generated,
# and the only real duplicate tree (f17-validation-real-yq-vendor-8x) was 61% tuning bytes. Kernel
# header/devel packages for two ABI versions of the same distribution, unpacked side by side, are a
# real (not generated) near-duplicate tree: most files (Kconfig, most headers, Makefiles) are
# byte-identical between the two versions, a minority (version.h, autoconf.h, a few point-release
# headers) differ -- unpacked with real_kernel_headers.py (dpkg-deb -x / rpm2cpio|cpio, payload only,
# no scripts run). One independence group per distribution/split, none shared with any other F17 item.
ITEMS += [
    item("f17-tuning-real-ubuntu-kernel-headers-2ver", "F17", "tuning", "medium", "build", "derived-from-real",
         {"inputs": [
             {"name": "common-a", "url": "https://archive.ubuntu.com/ubuntu/pool/main/l/linux/"
              "linux-headers-6.8.0-31_6.8.0-31.31_all.deb",
              "sha256": "b332a7edf4ea4b5124c52496b5a18d0c1858dd85b1d91fd4dba6f1e2978b3548", "size": 13608008,
              "notes": "SHA-256 from `apt-cache show`/Packages index, noble/main"},
             {"name": "generic-a", "url": "https://archive.ubuntu.com/ubuntu/pool/main/l/linux/"
              "linux-headers-6.8.0-31-generic_6.8.0-31.31_amd64.deb",
              "sha256": "dae8b1c95ad3a07d6a280c505cde6fa214bbc08db9e8ff75f58bbfab7ac991ae", "size": 3865730,
              "notes": "SHA-256 from `apt-cache show`/Packages index, noble/main"},
             {"name": "common-b", "url": "https://archive.ubuntu.com/ubuntu/pool/main/l/linux/"
              "linux-headers-6.8.0-139_6.8.0-139.139_all.deb",
              "sha256": "e01bc067f30ea622bdf87bf5ea60142070d805c1f449fc193332efada595da05", "size": 13604570,
              "notes": "SHA-256 from `apt-cache show`/Packages index, noble-updates/main"},
             {"name": "generic-b", "url": "https://archive.ubuntu.com/ubuntu/pool/main/l/linux/"
              "linux-headers-6.8.0-139-generic_6.8.0-139.139_amd64.deb",
              "sha256": "15bacf92d51a0ea971d9c1369c6385e8867cd4973eede8f8931fbaf99f3dd173", "size": 3755766,
              "notes": "SHA-256 from `apt-cache show`/Packages index, noble-updates/main"},
         ],
          "generator": gen("real_kernel_headers.py", 61006,
                           {"distro": "ubuntu-deb", "label_a": "6.8.0-31-generic", "label_b": "6.8.0-139-generic",
                            "inputs_a": ["common-a", "generic-a"], "inputs_b": ["common-b", "generic-b"]}),
          "output_pin": "TOFU"},
         lic("GPL-2.0-only WITH Linux-syscall-note", True, "Canonical Ltd. / Linux kernel contributors",
             "Ubuntu linux-headers-* packages; per-file SPDX identifiers as in the upstream kernel tree."),
         "ubuntu-noble-kernel-headers",
         "Real duplicate tree: Ubuntu noble linux-headers-6.8.0-31(-generic) and linux-headers-6.8.0-139(-generic) "
         "(base release vs. current noble-updates point release of the same 6.8 ABI) unpacked side by side into "
         "6.8.0-31-generic/ and 6.8.0-139-generic/ -- a real near-duplicate pair differing only in the point-release "
         "files (version.h, compile.h, a handful of patched headers).",
         tags=["real", "duplicate-tree", "kernel-headers"]),
    item("f17-validation-real-fedora-kernel-devel-2ver", "F17", "validation", "medium", "build", "derived-from-real",
         {"inputs": [
             {"name": "a", "url": "https://dl.fedoraproject.org/pub/fedora/linux/releases/44/Everything/x86_64/os/"
              "Packages/k/kernel-devel-6.19.10-300.fc44.x86_64.rpm",
              "sha256": "dfcc13793b3c0d1e12b28e89cddd6fd517adba8496be5768b21fa9952b677196", "size": 25313941,
              "notes": "Fedora 44 GA release tree, kernel-devel-6.19.10-300.fc44"},
             {"name": "b", "url": "https://dl.fedoraproject.org/pub/fedora/linux/updates/44/Everything/x86_64/"
              "Packages/k/kernel-devel-7.2.5-200.fc44.x86_64.rpm",
              "sha256": "ae1e721889284c078c5cf7c4a51524bbb4d665f69fe0c34ef39b20385e3af2fe", "size": 59320849,
              "notes": "Fedora 44 updates tree, kernel-devel-7.2.5-200.fc44"},
         ],
          "generator": gen("real_kernel_headers.py", 61007,
                           {"distro": "rpm", "label_a": "6.19.10-300.fc44", "label_b": "7.2.5-200.fc44",
                            "inputs_a": ["a"], "inputs_b": ["b"]}),
          "output_pin": "TOFU"},
         lic("GPL-2.0-only WITH Linux-syscall-note", True, "Fedora Project / Linux kernel contributors",
             "Fedora kernel-devel package; per-file SPDX identifiers as in the upstream kernel tree."),
         "fedora-kernel-devel",
         "Real duplicate tree: Fedora 44 kernel-devel-6.19.10-300.fc44 (GA release) and kernel-devel-7.2.5-200.fc44 "
         "(updates, a later kernel major/minor within the same Fedora release) unpacked side by side -- most build "
         "infrastructure files (Kconfig fragments, Makefiles, most headers) are identical or near-identical across "
         "the two kernel trees; the actual kernel version differs more than the Ubuntu tuning pair, giving a "
         "distinct duplicate/near-duplicate mix at validation.",
         tags=["real", "duplicate-tree", "kernel-headers"]),
    item("f17-heldout-real-almalinux-kernel-devel-2ver", "F17", "heldout", "medium", "build", "derived-from-real",
         {"inputs": [
             {"name": "a", "url": "https://vault.almalinux.org/10.0/AppStream/x86_64/os/Packages/"
              "kernel-devel-6.12.0-55.43.1.el10_0.x86_64.rpm",
              "sha256": "0950d88d1962ac4afb113176307856ac6f14b56a40dbc24edabe5a3e1fc7afb0", "size": 18509789,
              "notes": "AlmaLinux 10.0 (vault, minor release archive), kernel-devel-6.12.0-55.43.1.el10_0"},
             {"name": "b", "url": "https://repo.almalinux.org/almalinux/10/AppStream/x86_64/os/Packages/"
              "kernel-devel-6.12.0-211.53.1.el10_2.x86_64.rpm",
              "sha256": "541baa62df6d0fe8813ce0d6dba23e294b3dbfbcfa3e6846d491ca18a1a724b0", "size": 24289173,
              "notes": "AlmaLinux 10.2 (current repo), kernel-devel-6.12.0-211.53.1.el10_2"},
         ],
          "generator": gen("real_kernel_headers.py", 61008,
                           {"distro": "rpm", "label_a": "6.12.0-55.43.1.el10_0", "label_b": "6.12.0-211.53.1.el10_2",
                            "inputs_a": ["a"], "inputs_b": ["b"]}),
          "output_pin": "TOFU"},
         lic("GPL-2.0-only WITH Linux-syscall-note", True, "AlmaLinux OS Foundation / Linux kernel contributors",
             "AlmaLinux kernel-devel package; per-file SPDX identifiers as in the upstream kernel tree."),
         "almalinux-kernel-devel",
         "Held-out: real duplicate tree, AlmaLinux 10.0 and 10.2 kernel-devel-6.12.0-* (two EL10 minor releases of "
         "the same 6.12 kernel line) unpacked side by side. Distinct distribution/independence group from every "
         "tuning/validation F17 item (Ubuntu, Fedora); same construction (real_kernel_headers.py) but the version "
         "delta is minor-release erratum-sized rather than a cross-major kernel bump, giving a tighter/more-similar "
         "near-duplicate pair than the Fedora validation item.",
         notes="Held-out: distinct independence group from every tuning/validation F17 item.",
         tags=["real", "duplicate-tree", "kernel-headers"]),
]

# =======================================================================================
# F19 metadata-heavy filesystem trees
# =======================================================================================
ITEMS += [
    item("f19-tuning-zoo", "F19", "tuning", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71001, {"profile": "zoo", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-zoo",
         "Generated broad-coverage metadata tree: exhaustive permission matrix (all 4096 modes), varied uids/gids, "
         "user.*/trusted.*/security.* xattrs, access+default POSIX ACLs, hardlink groups (incl. 1000-link group), "
         "symlinks (relative/absolute/dangling/loop/chain), FIFOs, device nodes, a unix socket, Unicode/hostile/"
         "non-UTF-8 names, extreme mtimes (1901..2446).",
         tags=["generated"]),
    item("f19-tuning-rsnapshot-a", "F19", "tuning", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71002,
                           {"model": "rsnapshot", "base_files": 1500, "snapshots": 8, "change_fraction": 0.04})},
         GENERATED_LIC, "ebrc-g2-f19-rsnapshot-a",
         "Generated rsync --link-dest/rsnapshot-style rotating backup snapshots: oldest snapshot a full copy, each "
         "newer snapshot hardlinking unchanged files, writing changed files as new inodes, renaming directories "
         "(files stay hardlinked) and breaking links on metadata-only changes.",
         tags=["generated"]),
    item("f19-validation-deep", "F19", "validation", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71003, {"profile": "deep", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-deep",
         "Generated depth/width metadata tree: 1000-level one-character directory chain, near-PATH_MAX name chain, "
         "20000-entry directory, default-ACL inheritance through a subtree, symlinks climbing hundreds of levels, "
         "hardlinks between deepest and shallowest directories, xattrs on directories, non-Latin scripts.",
         tags=["generated"]),
    item("f19-validation-rsnapshot-b", "F19", "validation", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71004,
                           {"model": "rsnapshot", "base_files": 2000, "snapshots": 6, "change_fraction": 0.08})},
         GENERATED_LIC, "ebrc-g2-f19-rsnapshot-b",
         "Generated rsync --link-dest/rsnapshot-style rotating backup snapshots (independent seed/topology from "
         "f19-tuning-rsnapshot-a: more base files, fewer/higher-churn snapshots).",
         tags=["generated"]),
    item("f19-heldout-matrix", "F19", "heldout", "small", "generate", "generated",
         {"generator": gen("metadata_tree.py", 71005, {"profile": "matrix", "scale": 1.0})},
         GENERATED_LIC, "ebrc-g2-f19-matrix",
         "Generated owner x group x mode x ACL-variant cross-product metadata tree: xattr value-size ladder to the "
         "ext4 single-block limit, 255-byte xattr names, random Unicode/invalid-byte names, an alternatives-style "
         "symlink farm, a bin/sbin/usr-bin hardlink farm, uniformly random ext4-range timestamps, device nodes with "
         "random major/minor numbers.",
         notes="Held-out construction (metadata_tree.py's own docstring): a different profile from zoo/deep, never "
               "used in tuning/validation.",
         tags=["generated"]),
    item("f19-heldout-linkstore", "F19", "heldout", "medium", "generate", "generated",
         {"generator": gen("hardlink_farm.py", 71006, {"model": "linkstore", "packages": 40, "versions_max": 4})},
         GENERATED_LIC, "ebrc-g2-f19-linkstore",
         "Generated Nix-store-like tree after `nix-store --optimise`: read-only versioned package directories, "
         "identical files replaced by hardlinks into a content-addressed .links/ directory, .drv text files, and "
         "profile/gcroot symlink chains.",
         notes="Held-out construction (hardlink_farm.py's own docstring): a different model from rsnapshot, never "
               "used in tuning/validation.",
         tags=["generated"]),
]

# =======================================================================================
# F20 adversarial/high-entropy inputs
# =======================================================================================
ITEMS += [
    item("f20-tuning-csprng", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("csprng_files.py", 81001, {"mode": "files", "count": 60, "max_mib": 4})},
         GENERATED_LIC, "ebrc-g2-f20-csprng",
         "Generated maximal-entropy files from a seeded CSPRNG (SHAKE-256 counter mode): a fixed list of boundary "
         "sizes (powers of two +-1, 4 KiB edges, every gear-norm-v1 v2 policy's min/target/max +-1) plus "
         "log-uniform-sized files.",
         tags=["generated"]),
    item("f20-tuning-gear-extremes", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("gear_extremes.py", 81002, {"size_mib": 16, "dedup_blob_mib": 2, "dedup_copies": 6})},
         GENERATED_LIC, "ebrc-g2-f20-gear-extremes",
         "Generated CDC-adversarial inputs for the frozen gear-norm-v1 chunker: max-forcing (every chunk exactly "
         "max, i.e. CDC degenerates to fixed-size), min-forcing (every chunk exactly min), dedup-evading exact "
         "copies of a max-forcing blob at distinct residues, and boundary-length files. Verified against a "
         "vectorised reference chunker (cross-checked byte-for-byte against entrybound::chunker; see cdc_verify.sh).",
         tags=["generated"]),
    item("f20-tuning-bombs-dense", "F20", "tuning", "medium", "generate", "generated",
         {"generator": gen("compressible_bombs.py", 81003, {"mode": "dense", "scale": 0.3})},
         GENERATED_LIC, "ebrc-g2-f20-bombs-dense",
         "Generated highly compressible / codec-window-defeating files: dense zeros, single-byte and ASCII runs, "
         "a counter-incrementing log, random periods just beyond common match windows (deflate/zstd/brotli/xz), "
         "near-zero files with sparse random bytes, a repeated random block.",
         tags=["generated"]),
    item("f20-validation-aesctr", "F20", "validation", "medium", "generate", "generated",
         {"generator": gen("aes_ctr_ciphertext.py", 81004, {"plaintext_mib": 16, "keystream_mib": 32, "containers": 150})},
         GENERATED_LIC, "ebrc-g2-f20-aesctr",
         "Generated AES-256-CTR ciphertext (openssl enc, KAT-verified against NIST SP 800-38A F.5.5): near-duplicate "
         "plaintext versions under fresh IVs (no shared ciphertext) and under a reused IV (nonce-reuse misuse: "
         "ciphertext bytes shared wherever plaintext matches), pure keystream, and generic encrypted containers.",
         tags=["generated"]),
    item("f20-validation-bombs-compressed", "F20", "validation", "small", "generate", "generated",
         {"generator": gen("compressible_bombs.py", 81005,
                           {"mode": "compressed", "gz_gib": 1, "xz_gib": 1, "bz2_gib": 1, "zst_gib": 2,
                            "nested_gib": 1, "zip_entries": 8, "zip_entry_mib": 64, "tar_members": 4})},
         GENERATED_LIC, "ebrc-g2-f20-bombs-compressed",
         "Generated small compressed containers with huge expansion ratios: gzip/xz/bzip2/zstd of all-zero streams, "
         "triple-nested gzip, a flat zip of zero entries, a nested zip-of-zips, a tar.zst of zero members, and a "
         "POSIX tar with a 1 TiB sparse member (GNU tar --sparse).",
         notes="Corpus round-1 critic gap (F20 scale label, MINOR): this item was previously declared scale=large, "
               "which made coverage.md report a validation:large cell for F20 with no large *materialized* workload "
               "behind it (fits_smaller_tier: actual on-disk bytes are ~2 MiB, containers only). Relabeled to "
               "scale=small, matching materialized bytes. The adversarial expansion is real but notional: gzip/xz/"
               "bzip2/zstd of all-zero streams reach 1-2 GiB apparent per codec, the nested zip-of-zips and the "
               "tar.zst reach roughly similar apparent sizes, and the POSIX tar's one GNU --sparse member claims "
               "1 TiB apparent length while writing next to no real bytes. These expansion figures are recorded here "
               "(not in the scale field) so analyses that key off `scale` are not misled into expecting a large "
               "on-disk workload; f15-heldout-hugehole documents the same materialized-vs-apparent distinction for "
               "sparse files.",
         tags=["generated", "expansion:gz=1GiB", "expansion:xz=1GiB", "expansion:bz2=1GiB", "expansion:zst=2GiB",
               "expansion:nested-gz=1GiB", "expansion:tar-sparse-member=1TiB", "fits_smaller_tier"]),
    item("f20-validation-sparsedup", "F20", "validation", "medium", "generate", "generated",
         {"generator": gen("entropy_sparse_dup.py", 81006,
                           {"files": 16, "file_mib": 8, "blobs": 10, "blob_kib": [64, 256, 1024, 4096], "max_copies": 6})},
         GENERATED_LIC, "ebrc-g2-f20-sparsedup",
         "Generated maximal-entropy files with sparse exact duplication: a cdc-friendly variant (random blob copies "
         "at random offsets; CDC re-synchronises and finds duplicate chunks) and a cdc-hostile variant (gear-norm-v1 "
         "max-forcing everywhere outside the protected blob copies; offsets chosen so no chunk is ever duplicated "
         "although the blobs are). Verified with the reference chunker (0 duplicate chunks hostile, >0 friendly).",
         tags=["generated"]),
    item("f20-heldout-chacha-files", "F20", "heldout", "small", "generate", "generated",
         {"generator": gen("chacha20_containers.py", 81007, {"mode": "files", "count": 150, "xm": 16384, "cap_mib": 8, "sealed": 60})},
         GENERATED_LIC, "ebrc-g2-f20-chacha",
         "Generated ChaCha20 keystream and encrypted-container-like inputs (openssl enc -chacha20, cross-checked "
         "against an independent pure-Python RFC 8439 block function): Pareto-sized files fanned out by key byte, "
         "and generic sealed containers.",
         notes="Held-out: a different CSPRNG/cipher, size distribution and container layout from the "
               "tuning/validation F20 items (csprng_files.py, aes_ctr_ciphertext.py); per chacha20_containers.py's "
               "own docstring.",
         tags=["generated"]),
    item("f20-heldout-chacha-volume", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("chacha20_containers.py", 81008, {"mode": "volume", "volume_mib": 256, "backup_mib": 128})},
         GENERATED_LIC, "ebrc-g2-f20-chacha",
         "Generated encrypted-volume-like image: a 2 MiB header area (text metadata, random key slots) followed by "
         "ChaCha20 keystream, plus a sealed backup container. Same independence group and construction family as "
         "f20-heldout-chacha-files, at volume scale.",
         tags=["generated"]),
    item("f20-heldout-bombvariants", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("bomb_variants.py", 81009, {"scale": 0.15})},
         GENERATED_LIC, "ebrc-g2-f20-bombvariants",
         "Generated bomb-like and near-bomb inputs: brotli/lz4/lzip/multiblock-xz/multimember-gzip of all-zero "
         "streams, a 70000-empty-entry zip, a 200000-empty-member tar.gz, near-zero dense files.",
         notes="Held-out: a different generator from compressible_bombs.py (other codecs and container shapes, "
               "entry-count rather than byte-count blow-ups); per bomb_variants.py's own docstring.",
         tags=["generated"]),
    item("f20-heldout-gearstraddle", "F20", "heldout", "medium", "generate", "generated",
         {"generator": gen("gear_straddle.py", 81010, {"size_mib": 16})},
         GENERATED_LIC, "ebrc-g2-f20-gearstraddle",
         "Generated CDC-adversarial inputs targeting gear-norm-v1 mask transitions and near-misses: late-flood "
         "(matches every late mask but one early mask), near-miss (a bit set one above every policy's mask so "
         "nothing ever cuts), target-minus-one, alternating-min-max, trigger-bursts, and shifted-duplicate "
         "max-forcing blobs. Verified with the reference chunker.",
         notes="Held-out: a different generator from gear_extremes.py (targets mask transitions/near-misses "
               "instead of pure min/max forcing); per gear_straddle.py's own docstring.",
         tags=["generated"]),
]

# NOTE: an F20 structurally-adversarial-archives addition (libarchive/CPython/commons-compress/Go/
# fastzip-malo/Fifield-zipbomb-regen real items + two generated malicious_archives.py/_v2.py sets)
# was drafted and then held back, unwritten to sources.json, because the WSL2 VM used to run
# provision.py/make_sources.py became unresponsive before it could be validated/provisioned. The
# full draft is saved at (session scratchpad) f20-structural-block-pending.py and the new generator
# scripts it references already exist in this directory (decode_uu_files.py, malicious_archives.py,
# malicious_archives_v2.py, fifield_zipbomb_regen.py); see PROGRESS.md / the session's final report
# for how to resume.

DOC_NOTES = (
    "g2-generated corpus group: F04 many-small-file trees, F15 sparse files, F17 duplicate trees, F19 "
    "metadata-heavy filesystem trees, F20 adversarial/high-entropy inputs. Generated by "
    "research/corpus/generators/g2-generated/make_sources.py; edit the script, not this file. All items are "
    "materialized by the generator scripts in research/corpus/generators/g2-generated/ (each script's docstring "
    "documents its constructions, parameters and which split(s) it targets) except the F04 items reusing an "
    "already-provisioned F01/F03 item (kind=derive + copy-item): those carry real license terms from the source "
    "item. Docker was unavailable in this session (com.docker.service requires admin to start; the docker-desktop "
    "WSL VM never came up), so no docker-export items were added to this group; F04/F19 rely on generated content "
    "plus (F04 only) already-provisioned real trees instead of fresh docker exports of /usr/include, /usr/share/doc "
    "or /etc. F20's gear-norm-v1 adversarial generators (gear_extremes.py, gear_straddle.py, entropy_sparse_dup.py) "
    "embed a byte-identical vectorised reference chunker cross-checked against the real entrybound::chunker via "
    "cdc_verify.sh/cdc_verify.py (0 mismatches across all four v2 policies on every generated file, checked during "
    "authoring). Two stray probe scripts (.g2probe.py depth-walk smoke test, .g2probe.sh compressible_bombs "
    "determinism smoke test) and an unrelated leftover /root/eb-research/generated/EXP-SMOKE-000 directory (an "
    "ebr runner smoke-test artifact, not part of this corpus group) were found during resume; see PROGRESS.md for "
    "disposition. research/corpus/generators/g2-generated/ext4_image.py (a kind=derive generator that packs an "
    "existing item into a sparse ext4 image with mke2fs/debugfs/e2fsck) was reviewed and works (verified against "
    "e2fsprogs 1.47.0) but is not used by any item in this file; it remains available for future F15/F16 expansion."
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()
    items = json.loads(json.dumps(ITEMS))
    doc = {"schema": "ebrc-sources-v1", "notes": DOC_NOTES, "items": items}
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    if args.check_only:
        print(text)
        return
    SOURCES.parent.mkdir(parents=True, exist_ok=True)
    tmp = SOURCES.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, SOURCES)
    print(f"wrote {SOURCES} ({len(items)} items)")


if __name__ == "__main__":
    main()
