[package]
name = "entrybound"
description = "Core semantic model and native format foundations for Entrybound"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cap-std = "4.0.3"
crc32fast = "=1.5.0"
lz4_flex = { version = "=0.14.0", default-features = false, features = ["std", "safe-encode", "safe-decode", "checked-decode"] }
lzma-rust2 = { version = "=0.20.0", default-features = false, features = ["std", "encoder"] }
preflate-rs = "=0.7.6"
sha2 = "0.11.0"
zstd = { version = "=0.13.3", default-features = false, features = ["zdict_builder"] }

[dev-dependencies]
flate2 = "=1.1.9"
