[package]
name = "entrybound-cli"
description = "Command-line interface for Entrybound"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
autobins = false

[lib]
name = "entrybound_cli"
path = "src/lib.rs"

[[bin]]
name = "ebound"
path = "src/main.rs"

[[bin]]
name = "entrybound"
path = "src/bin/entrybound.rs"

[dependencies]
entrybound = { path = "../entrybound" }
rpassword = "=7.4.0"
zeroize = { version = "=1.9.0", features = ["alloc"] }

[lints]
workspace = true
