#!/usr/bin/env python3
"""Authoring helper: resolve a top-level PyPI requirement set into a fully pinned, hash-locked
requirements file (one wheel per package for CPython 3.12 / manylinux x86_64, binary only).

    /root/eb-research/venv/bin/python make_pip_lock.py <name> <req> [<req> ...]

writes ../locks/<name>.txt.  Resolution uses `pip install --dry-run --report` (pip 24.0) against
PyPI on the authoring date; the resulting lock, not PyPI's later state, defines the vendor tree.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main():
    name, reqs = sys.argv[1], sys.argv[2:]
    with tempfile.TemporaryDirectory() as td:
        report = Path(td) / "report.json"
        cmd = [sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed", "--only-binary=:all:",
               "--disable-pip-version-check", "--no-cache-dir", "--report", str(report), *reqs]
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)
        data = json.loads(report.read_text())
    lines = [f"# g1-code PyPI lock '{name}': generated by authoring/make_pip_lock.py with pip "
             f"{data.get('pip_version')} on CPython {sys.version.split()[0]} (linux x86_64)",
             "# top-level: " + " ".join(reqs)]
    rows = []
    for inst in data["install"]:
        meta = inst["metadata"]
        di = inst["download_info"]
        sha = di["archive_info"]["hashes"]["sha256"] if "hashes" in di.get("archive_info", {}) else \
            di["archive_info"]["hash"].split("=", 1)[1]
        if not di["url"].endswith(".whl"):
            raise SystemExit(f"{meta['name']}: not a wheel: {di['url']}")
        rows.append((meta["name"].lower(), meta["version"], sha, di["url"]))
    for n, v, sha, url in sorted(rows):
        lines.append(f"{n}=={v} \\\n    --hash=sha256:{sha}")
        lines.append(f"    # {url.rsplit('/', 1)[-1]}")
    out = HERE.parent / "locks" / f"{name}.txt"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out}: {len(rows)} packages")


if __name__ == "__main__":
    main()
