"""Generate a hash-pinned requirements file and a download manifest from a pip report.

Stdlib only (runs before the venv has any third-party packages).

Usage:
    python lockgen.py --report pip-report.json --wheel-dir DIR \
        --requirements OUT.txt --manifest OUT.json --retrieved 2026-09-12 \
        --top numpy scipy matplotlib pandas pyyaml psutil pytest
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from urllib.parse import unquote, urlparse


def canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", required=True)
    ap.add_argument("--wheel-dir", required=True)
    ap.add_argument("--requirements", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--retrieved", required=True)
    ap.add_argument("--top", nargs="+", required=True)
    args = ap.parse_args()

    with open(args.report, encoding="utf-8") as fh:
        report = json.load(fh)
    top = {canon(t) for t in args.top}
    entries = []
    for inst in report["install"]:
        name = inst["metadata"]["name"]
        version = inst["metadata"]["version"]
        info = inst["download_info"]
        url = info["url"]
        archive = info.get("archive_info", {})
        reported = archive.get("hashes", {}).get("sha256")
        if reported is None and archive.get("hash", "").startswith("sha256="):
            reported = archive["hash"].split("=", 1)[1]
        fname = unquote(os.path.basename(urlparse(url).path))
        local = os.path.join(args.wheel_dir, fname)
        if not os.path.isfile(local):
            print(f"missing downloaded file {local}", file=sys.stderr)
            return 2
        actual = sha256_file(local)
        if reported is not None and reported != actual:
            print(f"HASH MISMATCH {fname}: index={reported} local={actual}", file=sys.stderr)
            return 3
        entries.append(
            {
                "name": canon(name),
                "version": version,
                "top_level": canon(name) in top,
                "filename": fname,
                "url": url,
                "size_bytes": os.path.getsize(local),
                "sha256": actual,
                "retrieved": args.retrieved,
            }
        )
    entries.sort(key=lambda e: e["name"])
    missing = top - {e["name"] for e in entries}
    if missing:
        print(f"top-level packages missing from report: {sorted(missing)}", file=sys.stderr)
        return 4

    env = report.get("environment", {})
    lines = [
        "# Pinned, hash-locked requirements for the ebr research tooling.",
        "# Target: /root/eb-research/venv (WSL Ubuntu 24.04, CPython "
        + env.get("python_full_version", "3.12")
        + ", "
        + env.get("platform_machine", "x86_64")
        + ").",
        "# Generated by research/tools/lock_requirements.sh via lockgen.py on "
        + args.retrieved
        + "; do not edit by hand.",
        "# Download URLs, sizes and SHA-256 are recorded in requirements-downloads.json.",
        "# Install: pip install --require-hashes --no-deps -r requirements.txt",
        "",
        "# --- top-level ---",
    ]
    for group, want_top in (("top", True), ("transitive", False)):
        if group == "transitive":
            lines.append("")
            lines.append("# --- transitive ---")
        for e in entries:
            if e["top_level"] is want_top:
                lines.append(f"{e['name']}=={e['version']} \\")
                lines.append(f"    --hash=sha256:{e['sha256']}")
    with open(args.requirements, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    manifest = {
        "schema": "ebr.downloads.v1",
        "purpose": "Wheels installed into /root/eb-research/venv for research/tools (ebr)",
        "retrieved": args.retrieved,
        "index": "https://pypi.org/simple",
        "pip_version": report.get("pip_version"),
        "environment": {
            k: env.get(k)
            for k in ("implementation_name", "python_full_version", "platform_machine", "sys_platform")
        },
        "files": entries,
    }
    with open(args.manifest, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=False)
        fh.write("\n")
    print(f"locked {len(entries)} distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
